export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const CLEAR_FAVOURITES = 'CLEAR_FAVOURITES';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';

export const GET_COLORS = 'GET_COLORS';
export const GET_MANUFACTURERS = 'GET_MANUFACTURERS';

export const CLEAR_CAR_DETAILS = 'CLEAR_CAR_DETAILS';
export const GET_CAR_DETAILS = 'GET_CAR_DETAILS';
export const GET_CARS = 'GET_CARS';
