export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const CLEAR_FAVOURITES = 'CLEAR_FAVOURITES';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';

export const GET_COLORS = 'GET_COLORS';
export const GET_MANUFACTURERS = 'GET_MANUFACTURERS';
